export type AppCommand =
  | 'new'
  | 'newWindow'
  | 'open'
  | 'openFolder'
  | 'save'
  | 'saveAs'
  | 'revertToSaved'
  // Internal (main -> renderer): the user chose "Save" in the window-close guard.
  // The renderer saves EVERY dirty tab (writing each tab's snapshot, prompting a
  // Save As for path-less tabs) and reports window-level dirtiness clean, letting
  // the main close-guard complete the close. Not shown in any menu.
  | 'saveAllAndClose'
  // Internal (main -> renderer): the user chose "Don't Save" in the window-close
  // guard. The renderer discards EVERY tab's crash backup and marks all clean,
  // letting the main close-guard complete the close WITHOUT writing any file.
  // Not shown in any menu.
  | 'discardAllAndClose'
  | 'showInFinder'
  | 'revealInFileTree'
  | 'revealInLibrary'
  | 'duplicateFile'
  | 'renameFile'
  | 'moveFileTo'
  | 'deleteFile'
  | 'getInfo'
  | 'print'
  | 'share'
  | 'toggleSource'
  | 'toggleSidebar'
  | 'find'
  | 'replace'
  | 'bold'
  | 'italic'
  | 'strikethrough'
  | 'inlineCode'
  | 'underline'
  | 'highlight'
  | 'superscript'
  | 'subscript'
  | 'clearFormatting'
  | 'selectLine'
  | 'selectBlock'
  | 'jumpToTop'
  | 'jumpToBottom'
  | 'link'
  | 'insertImage'
  | 'heading1'
  | 'heading2'
  | 'heading3'
  | 'heading4'
  | 'heading5'
  | 'heading6'
  | 'paragraph'
  | 'increaseHeading'
  | 'decreaseHeading'
  | 'indent'
  | 'outdent'
  | 'bulletList'
  | 'orderedList'
  | 'taskList'
  | 'blockquote'
  | 'codeBlock'
  | 'horizontalRule'
  | 'undo'
  | 'redo'
  | 'exportHtml'
  | 'exportPdf'
  | 'exportDocx'
  | 'exportEpub'
  | 'exportRtf'
  | 'exportLatex'
  | 'exportOpml'
  | 'toggleFocusMode'
  | 'toggleTypewriterMode'
  | 'toggleStatusBar'
  | 'toggleAlwaysOnTop'
  | 'nextTab'
  | 'previousTab'
  | 'closeTab'
  | 'openThemeFolder'
  | 'reloadThemes'
  | 'preferences'
  | 'copyAsHtml'
  | 'copyAsMarkdown'
  | 'copyAsPlainText'
  | 'copyWithoutStyling'
  | 'pasteAsPlainText'
  | 'eolLf'
  | 'eolCrlf'
  // Window zoom (View menu). Custom commands instead of Electron's zoom roles:
  // the renderer routes them through the zoom:adjust IPC so it learns the new
  // factor and can zoom-compensate the native-anchored chrome (sidebar toggle,
  // traffic-light clearances), which OS pixels do not scale with page zoom.
  | 'zoomIn'
  | 'zoomOut'
  | 'zoomReset'
  | 'commandPalette'
  | 'quickOpen'
  | 'presentation'
  | 'newFromTemplate'
