#!/usr/bin/env bash
#
# make-icon.sh - Regenerate the macOS app icon from build/icon.png.
#
# build/icon.png (1024x1024 RGBA) is the source of truth, generated by
# scripts/make-icon.py. This script rasterizes the required icon sizes with
# `sips` and packs them into build/icon.icns with `iconutil` (both ship with
# macOS - no extra tooling required).
#
# Usage:  bash scripts/make-icon.sh
#
# electron-builder picks up build/icon.icns automatically (buildResources: build).
set -euo pipefail

cd "$(dirname "$0")/.."

SRC="build/icon.png"
ICONSET="build/icon.iconset"

if [[ ! -f "$SRC" ]]; then
  echo "Missing $SRC - run: python3 scripts/make-icon.py" >&2
  exit 1
fi

rm -rf "$ICONSET"
mkdir -p "$ICONSET"

for s in 16 32 128 256 512; do
  sips -z "$s" "$s"     "$SRC" --out "$ICONSET/icon_${s}x${s}.png"    >/dev/null
  d=$((s * 2))
  sips -z "$d" "$d"     "$SRC" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
done

iconutil -c icns "$ICONSET" -o build/icon.icns
rm -rf "$ICONSET"

echo "Wrote build/icon.icns"
